config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about' => 'about#index', as: :about
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :quotes

  match '*path' => 'application#error404', via: :all

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  mount_uploader :author_image, AuthorImageUploader
  belongs_to :poster, class_name: 'User', foreign_key: :poster_id

  validates :author_name, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 250 }, presence: true
  validates :source, length: { maximum: 250 }

  def created_by?(user)
    return false unless user
    poster_id == user.id
  end

  private

  def self.ransackable_attributes(auth_object = nil)
    super & %w(content author_name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_quotes, class_name: 'Quote', foreign_key: :poster_id

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    name = auth_hash[:info][:name]
    image_url = auth_hash[:info][:image]

    user = User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.name = name
      user.image_url = image_url
    end

    user.assign_attributes(nickname: nickname, name: name, image_url: image_url)

    user.save! if user.changed?

    user
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @num_users = User.count
    @num_quotes = Quote.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  before_action :build_universal_search

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  # The number of quotes shown in index per page
  PER = 10

  private

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return unless logged_in?
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインする必要があります'
  end

  def error404(e)
    render 'error404', status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render 'error500', status: 500, formats: [:html]
  end

  def build_universal_search
    @q = Quote.page(params[:page]).per(PER).includes(:poster).order(updated_at: :desc).ransack(params[:q])
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate, except: :show

  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = current_user.created_quotes.build
  end

  def create
    @quote = current_user.created_quotes.build(quote_params)
    if @quote.save
      redirect_to @quote, notice: '名言を登録しました'
    else
      render :new
    end
  end

  def edit
    @quote = current_user.created_quotes.find(params[:id])
  end

  def update
    @quote = current_user.created_quotes.find(params[:id])
    if @quote.update(quote_params)
      redirect_to @quote, notice: '名言を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @quote = current_user.created_quotes.find(params[:id])
    @quote.destroy!
    redirect_to root_path, notice: '名言を削除しました'
  end

  private

  def quote_params
    params.require(:quote).permit(
      :author_name, :source, :content, :author_image, :author_image_cache
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @quotes = @q.result
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Sets title
  def title(page_title)
    content_for(:title) { page_title }
  end

  # Creates an icon tag given an icon name and possible icon modifiers.
  # A non-breaking space entity will be put between an icon and a text.
  #
  #
  # Examples
  #
  #   fa_icon_spaced "camera-retro", text: "Take a photo"
  #   # => <i class="fa fa-camera-retro"></i> &nbsp; Take a photo
  #
  def fa_icon_spaced(names = "flag", options = {})
    classes = ["fa"]
    classes.concat Private.icon_names(names)
    classes.concat Array(options.delete(:class))
    text = options.delete(:text)
    right_icon = options.delete(:right)
    icon = content_tag(:i, nil, options.merge(:class => classes))
    Private.icon_join(icon, text, right_icon, true)
  end

  module Private
    extend ActionView::Helpers::OutputSafetyHelper

    def self.icon_join(icon, text, reverse_order = false, spaced = false)
      return icon if text.blank?
      elements = [icon, ERB::Util.html_escape(text)]
      elements.reverse! if reverse_order
      elements.insert(1, "&nbsp;".html_safe) if spaced
      safe_join(elements, " ")
    end

    def self.icon_names(names = [])
      array_value(names).map { |n| "fa-#{n}" }
    end

    def self.array_value(value = [])
      value.is_a?(Array) ? value : value.to_s.split(/\s+/)
    end
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<% title 'Quologia について' %>

<header class="page-heading">
  <h3>Quologia</h3>
</header>

<main class="about">
  <div class="logo-container">
    <%= image_tag 'logo.svg', width: 150, height: 150, class: 'logo', alt: 'Quologia' %>
  </div>

  <table class="site-meta-table">
    <tbody>
      <tr>
        <td align="right">サービス名</td>
        <td>Quologia</td>
      </tr>
      <tr>
        <td align="right">サービス名の読み</td>
        <td>クオロギア</td>
      </tr>
      <tr>
        <td align="right">動機</td>
        <td><i class="fa fa-external-link-square"></i> <a href="http://rubyonrails.org/">Ruby on Rails</a> の学習</td>
      </tr>
      <tr>
        <td align="right">機能</td>
        <td>名言の閲覧，検索，および投稿</td>
      </tr>
      <tr>
        <td align="right">開発・運営</td>
        <td><i class="fa fa-external-link-square"></i> <a href="http://lambdar.me/">Naoto Yokoyama</a></td>
      </tr>
      <tr>
        <td align="right">ロゴデザイン</td>
        <td><i class="fa fa-twitter-square"></i> <a href="https://twitter.com/honeshabri">@honeshabri</a></td>
      </tr>
      <tr>
        <td align="right">連絡先</td>
        <td>
          <i class="fa fa-twitter-square"></i> <a href="https://twitter.com/quologia">@quologia</a><br/>
          <i class="fa fa-envelope"></i> <%= mail_to 'support@quologia.com', nil, encode: 'hex' %>
        </td>
      </tr>
      <tr>
        <td align="right">総ユーザ数</td>
        <td><%= @num_users %></td>
      </tr>
      <tr>
        <td align="right">総名言数</td>
        <td><%= @num_quotes %></td>
      </tr>
      <tr>
        <td align="right">ソースコード</td>
        <td><i class="fa fa-github-square"></i> <a href="https://github.com/builtinnya/quologia">builtinnya/quologia</a></td>
      </tr>
      <tr>
        <td align="right">公開日</td>
        <td>2015-07-20</td>
      </tr>
      <tr>
        <td align="right">利用規約</td>
        <td>
          <i class="fa fa-github-square"></i> <a href="https://github.com/builtinnya/quologia-policy/blob/master/terms-of-service.markdown">利用規約</a><br/>
          <i class="fa fa-github-square"></i> <a href="https://github.com/builtinnya/quologia-policy/blob/master/privacy-policy.markdown">プライバシーポリシー</a>
        </td>
      </tr>
    </tbody>
  </table>
</main>

app/views/application/error404.html.erb
<div class="alert">
  <h1>404 エラー</h1>
  <ul>
    <li>ご指定のページは存在しません</li>
  </ul>
</div>

app/views/application/error500.html.erb
<div class="alert">
  <h1>500 エラー</h1>
  <ul>
    <li>エラーが発生しました</li>
  </ul>
</div>

app/views/layouts/_fb.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=114132705595982";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_fb_share.html.erb
<div class="fb-share-button" data-layout="box_count"></div>

app/views/layouts/_ga.html.erb
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-65299680-1', 'auto');
 ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<div class="navbar" data-ks-navbar>
  <nav>
    <ul>
      <li class="navbar-title">
        <%= link_to 'Quologia', root_path %>
        <button role="button">=</button>
      </li>
      <li>
        <%= search_form_for(@q, url: root_path, class: 'header-search-form') do |f| %>
          <%= f.search_field :content_or_author_name_or_poster_name_cont, placeholder: '検索する' %>
        <% end %>
      </li>
      <li>
        <%= link_to(about_path) do %>
          <%= fa_icon_spaced 'info-circle', text: 'About' %>
        <% end %>
      </li>
    </ul>
    <ul>
      <% if logged_in? %>
        <li>
          <%= link_to(new_quote_path) do %>
            <%= fa_icon_spaced 'plus-square', text: '名言' %>
          <% end %>
        </li>
        <li>
          <%= image_tag current_user.image_url, class: 'user-header-menu-top-icon' %>
          <span class="user-header-menu-top-text"><%= current_user.name %></span>
          <ul>
            <li>
              <%= link_to(logout_path) do %>
                <%= fa_icon_spaced 'sign-out', text: 'ログアウト' %>
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= fa_icon_spaced 'sign-in', text: 'ログイン' %>
          <ul>
            <li>
              <%= link_to('/auth/twitter') do %>
                <%= fa_icon_spaced 'twitter-square lg', text: 'Twitter' %>
              <% end %>
            </li>
            <li>
              <%= link_to('/auth/facebook') do %>
                <%= fa_icon_spaced 'facebook-square lg', text: 'Facebook' %>
              <% end %>
            </li>
            <li>
              <%= link_to('/auth/github') do %>
                <%= fa_icon_spaced 'github-square lg', text: 'GitHub' %>
              <% end %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_notice.html.erb
<%= javascript_tag do %>
 (function() {
   function pageLoadListener() {
     ready();
     $(this).off('page:load', pageLoadListener);
   };
   var ready = function() {
     var notice = <%= raw flash[:notice].to_json %>;
     var alert = <%= raw flash[:alert].to_json %>;

     if (notice) {
       k$.status({ text: notice, type: 'status-blue' });
     } else if (alert) {
       k$.status({ text: alert, type: 'status-red' });
     }

     $(this).off('page:load', pageLoadListener);
   };
   $(document).on('ready', ready);
   $(document).on('page:load', pageLoadListener);
 })();
<% end %>

app/views/layouts/_tw_share.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-via="quologia" data-size="default" data-related="quologia" data-hashtags="quologia" data-count="vertical">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : 'Quologia' %></title>
  <%= display_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/ga" %>
</head>
<body>
  <%= render "layouts/notice" %>
  <%= render "layouts/header" %>
  <div class="wrapper">
    <%= yield %>
  </div>
</body>
</html>

app/views/quotes/_empty.html.erb
<div class="alert">
  <h1>名言が見つかりません</h1>
</div>

app/views/quotes/_quote.html.erb
<div class="quote-container">
  <div class="quote-author-image">
    <%= link_to(quote) do %>
      <%= image_tag quote.author_image.url, class: 'user-author-image' %>
      <div class="after"><span>詳細</span></div>
    <% end %>
  </div>
  <div class="quote-main">
    <div class="quote-main-container">
      <div class="quote-content">
        <blockquote>
          <%= quote.content %>
          <cite>
            <%= link_to root_path(q: { author_name_eq: quote.author_name }) do %>
              <%= quote.author_name %>
            <% end %>
          </cite>
        </blockquote>
      </div>
    </div>
  </div>
</div>

app/views/quotes/_seo.html.erb
<!-- Open Graph -->
<% set_meta_tags og: {
  url: canonical_href,
  title: quote.author_name,
  description: quote.content,
  site_name: 'Quologia',
  image: quote.author_image.url,
  app_id: Rails.application.secrets.facebook_api_id
} %>

<!-- Twitter Card -->
<% set_meta_tags twitter: {
  card: 'summary',
  site: '@quologia',
  title: quote.author_name,
  description: quote.content,
  image: quote.author_image.url
} %>

app/views/quotes/edit.html.erb
<% title "名言編集" %>

<header class="page-heading">
  <h3>名言編集</h3>
</header>

<main class="edit-quote">
  <%= form_for(@quote, role: 'form') do |f| %>
    <% if @quote.errors.any? %>
      <div class="alert">
        <h1>エラー</h1>
        <ul>
          <% @quote.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="author-image">
      <div class="author-image-display">
        <% if @quote.author_image? %>
          <%= image_tag @quote.author_image.url, class: 'user-author-image' %>
        <% else %>
          <%= image_tag 'author-default.png', class: 'user-author-image' %>
        <% end %>
      </div>
      <div>
        <%= f.file_field :author_image %>
        <%= f.hidden_field :author_image_cache %>
      </div>
    </div>

    <div class="author-profile">
      <div class="form-group author-name">
        <%= f.text_field :author_name, size: 30, class: ('error' if @quote.errors[:author_name].any?), placeholder: t('activerecord.attributes.quote.author_name') %>
      </div>
    </div>

    <div class="form-group quote-source">
      <%= f.text_field :source, size: 30, class: ('error' if @quote.errors[:source].any?), placeholder: t('activerecord.attributes.quote.source') %>
    </div>

    <div class="form-group quote-content">
      <%= f.text_area :content, rows: 4, cols: 30, class: ('error' if @quote.errors[:content].any?), placeholder: t('activerecord.attributes.quote.content') %>
    </div>

    <div class="agreement-notice">
      投稿する前に，必ず<a href="https://github.com/builtinnya/quologia-policy/blob/master/terms-of-service.markdown">利用規約</a>をお読み下さい．
    </div>

    <div class="submit">
      <%= f.submit '更新する', role: 'button', data: { disable_with: '更新中…' } %>
    </div>
  <% end %>
</main>

app/views/quotes/new.html.erb
<% title "名言登録" %>

<header class="page-heading">
  <h3>名言登録</h3>
</header>

<main class="new-quote">
  <%= form_for(@quote, role: 'form') do |f| %>
    <% if @quote.errors.any? %>
      <div class="alert">
        <h1>エラー</h1>
        <ul>
          <% @quote.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="author-image">
      <div class="author-image-display">
        <% if @quote.author_image? %>
          <%= image_tag @quote.author_image.url, class: 'user-author-image' %>
        <% else %>
          <%= image_tag 'author-default.png', class: 'user-author-image' %>
        <% end %>
      </div>
      <div>
        <%= f.file_field :author_image %>
        <%= f.hidden_field :author_image_cache %>
      </div>
    </div>

    <div class="author-profile">
      <div class="form-group author-name">
        <%= f.text_field :author_name, size: 30, class: ('error' if @quote.errors[:author_name].any?), placeholder: t('activerecord.attributes.quote.author_name') %>
      </div>
    </div>

    <div class="form-group quote-source">
      <%= f.text_field :source, size: 30, class: ('error' if @quote.errors[:source].any?), placeholder: t('activerecord.attributes.quote.source') %>
    </div>

    <div class="form-group quote-content">
      <%= f.text_area :content, rows: 4, cols: 30, class: ('error' if @quote.errors[:content].any?), placeholder: t('activerecord.attributes.quote.content') %>
    </div>

    <div class="agreement-notice">
      投稿する前に，必ず<a href="https://github.com/builtinnya/quologia-policy/blob/master/terms-of-service.markdown">利用規約</a>をお読み下さい．
    </div>

    <div class="submit">
      <%= f.submit '登録する', role: 'button', data: { disable_with: '登録中…' } %>
    </div>
  <% end %>
</main>

app/views/quotes/show.html.erb
<% title "\"#{@quote.content}\" - #{@quote.author_name}" %>

<% render partial: 'quotes/seo', locals: { quote: @quote } %>
<%= render 'layouts/fb' %>

<header class="page-heading">
  <h3>名言</h3>
</header>

<main class="show-quote">
  <% if @quote.created_by?(current_user) %>
    <div class="quote-buttons">
      <%= link_to '編集する', edit_quote_path(@quote), class: 'quote-edit-button' %>
      &nbsp;
      <%= link_to '削除する', quote_path(@quote), class: 'quote-delete-button', method: :delete, data: { confirm: '本当に削除しますか？' } %>
     </div>
  <% end %>
  <%= render partial: 'quotes/quote', locals: { quote: @quote } %>
  <table class="quote-meta-table">
    <tbody>
      <tr>
        <td align="right">投稿者</td>
        <td>
          <% if @quote.poster %>
            <% if @quote.poster.image_url %>
              <%= image_tag @quote.poster.image_url, class: 'poster-image' %>
            <% end %>
            <%= link_to root_path(q: { poster_name_eq: @quote.poster.name }) do %>
              <span class="poster-name-text"><%= @quote.poster.name %></span>
            <% end %>
          <% else %>
            <span class="deleted-poster">退会済み</span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td align="right">投稿日時</td>
        <td><%= @quote.created_at %>
      </tr>
      <tr>
        <td align="right">最終更新日時</td>
        <td><%= @quote.updated_at %></td>
      </tr>
      <tr>
        <td align="right">出典</td>
        <td><%= @quote.source %></td>
      </tr>
    </tbody>
  </table>


  <div class="social-buttons">
    <ul>
      <li><%= render "layouts/tw_share" %></li>
      <li><%= render "layouts/fb_share" %></li>
    </ul>
  </div>

  <div id="disqus_thread"></div>
  <script type="text/javascript" data-turbolink-track="false">
   /* * * CONFIGURATION VARIABLES * * */
   var disqus_shortname = 'quologia';
   var disqus_identifier = '/quotes/' + '<%= @quote.id %>';

   /* * * DON'T EDIT BELOW THIS LINE * * */
   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</main>

app/views/welcome/index.html.erb
<header class="page-heading">
  <h3>名言集</h3>
</header>

<main class="quote-list">
  <% if @quotes.empty? %>
    <%= render 'quotes/empty' %>
  <% else %>
    <% @quotes.each do |quote| %>
      <%= render partial: 'quotes/quote', locals: { quote: quote } %>
    <% end %>
  <% end %>

  <%= paginate @quotes, window: 2, outer_window: 3 %>
</main>